{"name": "Login without entering any credentials", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62554): Max retries exceeded with url: /session/82e5f32a3ed4a8c0afebd92958849dab/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B76FDC4150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 61, in is_blank_login\n    LoginPage.is_invalid_user(login)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\LoginPage.py\", line 135, in is_invalid_user\n    invalid_login = self.get_invalid_login()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\LoginPage.py\", line 105, in get_invalid_login\n    return self.find_element(*Locator.invalid_login)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 21, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Launch the browser", "status": "passed", "start": 1691072358178, "stop": 1691072359149}, {"name": "When Open the https://courses.ultimateqa.com/users/sign_in website", "status": "passed", "start": 1691072359150, "stop": 1691072361149}, {"name": "Then The login portal has been opened", "status": "passed", "start": 1691072361149, "stop": 1691072361156}, {"name": "When Provide the email \"\" and password \"\"", "status": "passed", "start": 1691072361156, "stop": 1691072361229}, {"name": "Then Please enter a valid email address and This field cannot be blank message is displayed", "status": "passed", "start": 1691072361229, "stop": 1691072361368}, {"name": "Then Click on the Sign in button", "status": "passed", "start": 1691072361368, "stop": 1691072361427}, {"name": "Then Login is failed and invalid email or password message is displayed", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62554): Max retries exceeded with url: /session/82e5f32a3ed4a8c0afebd92958849dab/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B76FDC4150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 61, in is_blank_login\n    LoginPage.is_invalid_user(login)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\LoginPage.py\", line 135, in is_invalid_user\n    invalid_login = self.get_invalid_login()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\LoginPage.py\", line 105, in get_invalid_login\n    return self.find_element(*Locator.invalid_login)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 21, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1691072361427, "stop": 1691072390011}, {"name": "Then Close the browser", "status": "skipped", "start": 1691072390012, "stop": 1691072390012}], "start": 1691072358178, "stop": 1691072390012, "uuid": "331a097e-be11-434c-bdbd-cf771af59b8c", "historyId": "32eca274abcca309f9c4df47253e37a5", "fullName": "Validate the login feature: Login without entering any credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Validate the login feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}