{"name": "Login with valid credentials", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50238): Max retries exceeded with url: /session/993e2cb0a85d658b3ca937b80f34c73c/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE063F9ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 24, in is_login_successfully\n    home = HomePage(context.driver)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 11, in __init__\n    self.is_home_available(new_user)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 24, in is_home_available\n    self.wait_element_clickable(*Locator.user_dropdown)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 105, in wait_element_clickable\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 312, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Launch the browser", "status": "passed", "start": 1691073806681, "stop": 1691073807945}, {"name": "When Open the https://courses.ultimateqa.com/users/sign_in website", "status": "passed", "start": 1691073807945, "stop": 1691073810100}, {"name": "Then The login portal has been opened", "status": "passed", "start": 1691073810100, "stop": 1691073810109}, {"name": "When Provide the email \"jfilipesousa1991@gmail.com\" and password \"testesmartex\"", "status": "passed", "start": 1691073810109, "stop": 1691073810352}, {"name": "Then Click on the Sign in button", "status": "passed", "start": 1691073810352, "stop": 1691073810416}, {"name": "Then Login is successful and dashboard is opened", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50238): Max retries exceeded with url: /session/993e2cb0a85d658b3ca937b80f34c73c/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE063F9ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 24, in is_login_successfully\n    home = HomePage(context.driver)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 11, in __init__\n    self.is_home_available(new_user)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\HomePage.py\", line 24, in is_home_available\n    self.wait_element_clickable(*Locator.user_dropdown)\n  File \"C:\\Users\\Joao Sousa\\PycharmProjects\\behave\\features\\pages\\BasePage.py\", line 105, in wait_element_clickable\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 312, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Joao Sousa\\AppData\\Roaming\\Python\\Python311\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1691073810416, "stop": 1691073838855}, {"name": "Then Logout the application", "status": "skipped", "start": 1691073838855, "stop": 1691073838855}, {"name": "Then Close the browser", "status": "skipped", "start": 1691073838855, "stop": 1691073838855}], "start": 1691073806681, "stop": 1691073838855, "uuid": "b44e74e0-02da-4927-ae04-dd0c9631ce58", "historyId": "76dbc8b56014fea2368cedd600771420", "fullName": "Login scenarios: Login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login scenarios"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}